name: UTMTL
channels:
  - pytorch
  - conda-forge
  - anaconda
  - cyclus 
  - defaults
dependencies:
  - java-jre 
  - _ipyw_jlab_nb_ext_conf
  - _tflow_190_select
  - absl-py
  - alabaster
  - anaconda
  - anaconda-client
  - anaconda-navigator
  - anaconda-project
  - astor
  - astropy
  - attrs
  - backcall
  - backports
  - backports.shutil_get_terminal_size
  - beautifulsoup4
  - bitarray
  - bkcharts
  - blaze
  - bleach
  - blosc
  - boto
  - bottleneck
  - bzip2
  - ca-certificates
  - cairo
  - cffi
  - chardet
  - click
  - cloudpickle
  - clyent
  - colorama
  - conda-verify
  - contextlib2
  - cryptography
  - cudatoolkit
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - datashape
  - decorator
  - docutils
  - entrypoints
  - et_xmlfile
  - expat
  - fastcache
  - flask
  - flask-cors
  - fontconfig
  - freetype
  - gast
  - get_terminal_size
  - gevent
  - glib
  - glob2
  - gmpy2
  - graphite2
  - greenlet
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - html5lib
  - icu
  - idna
  - intel-openmp
  - ipython_genutils
  - itsdangerous
  - jbig
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - lazy-object-proxy
  - libcurl
  - libffi
  - libpng
  - libsodium
  - libssh2
  - libtiff
  - libxcb
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - lzo
  - markdown
  - markupsafe
  - matplotlib
  - mccabe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - more-itertools
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - navigator-updater
  - nbconvert
  - nbformat
  - ninja
  - nltk
  - nose
  - numba
  - numexpr
  - numpy
  - numpy-base
  - odo
  - openssl
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - pango
  - parso
  - partd
  - path.py
  - pcre
  - pep8
  - pickleshare
  - pillow
  - pixman
  - pkginfo
  - pluggy
  - prompt_toolkit
  - psutil
  - ptyprocess
  - py
  - pycosat
  - pycparser
  - pycrypto
  - pycurl
  - pyflakes
  - pygments
  - pyodbc
  - pyparsing
  - pyqt
  - pysocks
  - pytables
  - pytest-arraydiff
  - pytest-astropy
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python=3.6.5
  - python-dateutil
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtawesome
  - qtconsole
  - qtpy
  - requests
  - rope
  - ruamel_yaml
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - send2trash
  - simplegeneric
  - singledispatch
  - sip
  - six
  - snappy
  - snowballstemmer
  - sphinxcontrib
  - sphinxcontrib-websupport
  - sqlalchemy
  - sqlite
  - statsmodels
  - sympy
  - tblib
  - tensorboard
  - tensorflow
  - tensorflow-base
  - terminado
  - testpath
  - tk
  - toolz
  - traitlets
  - unicodecsv
  - urllib3
  - wcwidth
  - webencodings
  - werkzeug
  - wrapt
  - xlrd
  - xlsxwriter
  - xlwt
  - xz
  - yaml
  - zeromq
  - zict
  - asn1crypto
  - astroid
  - babel
  - blas
  - bokeh
  - certifi
  - distributed
  - filelock
  - flann
  - imageio
  - imagesize
  - ipykernel
  - ipython
  - ipywidgets
  - isort
  - jdcal
  - jupyter_client
  - jupyterlab
  - jupyterlab_launcher
  - libprotobuf
  - multipledispatch
  - networkx
  - notebook
  - numpydoc
  - olefile
  - openpyxl
  - pathlib2
  - patsy
  - pexpect
  - pip
  - ply
  - protobuf
  - pycodestyle
  - pylint
  - pyopenssl
  - pytest
  - setuptools
  - sortedcollections
  - sortedcontainers
  - sphinx
  - spyder
  - tensorboardx
  - termcolor
  - tornado
  - tqdm
  - typing
  - wheel
  - widgetsnbextension
  - pytorch
  - torchvision
  - pip:
    - tables==3.4.3
    - ujson==1.35
    - bpemb
    - opencv-python

